/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Check IP": {                                    "en": "Check IP",                                        "de": "Überprüfen Sie die IP-Adresse",                   "ru": "Проверьте IP-адрес",                              "pt": "Verifique o endereço IP",                         "nl": "Controleer het IP-adres",                         "fr": "Vérifiez l'adresse IP",                           "it": "Controlla l'indirizzo IP",                        "es": "Compruebe la dirección IP",                       "pl": "Sprawdź adres IP"},
    "IP address of the Fronius inverter": {          "en": "IP address of the Fronius inverter",              "de": "IP-Adresse des Fronius Wechselrichters",          "ru": "IP-адрес инвертора Fronius",                      "pt": "Endereço IP do inversor Fronius",                 "nl": "IP-adres van de Fronius-omvormer",                "fr": "Adresse IP de l'onduleur Fronius",                "it": "Indirizzo IP dell'inverter Fronius",              "es": "Dirección IP del inversor Fronius.",              "pl": "Adres IP falownika Fronius"},
    "IP(192.168.x.x) or URL(sub.domain.tld)": {      "en": "IP(192.168.x.x) or URL(sub.domain.tld)",          "de": "IP (192.168.x.x) oder URL (Subdomäne.tld)",       "ru": "IP (192.168.x.x) или URL (subdomain.tld)",        "pt": "IP (192.168.x.x) ou URL (subdomínio.tld)",        "nl": "IP (192.168.x.x) of URL (subdomain.tld)",         "fr": "IP (192.168.x.x) ou URL (subdomain.tld)",         "it": "IP (192.168.x.x) o URL (sottodominio.tld)",       "es": "IP (192.168.x.x) o URL (subdominio.tld)",         "pl": "IP (192.168.x.x) lub URL (subdomain.tld)"},
    "Polling interval in seconds.": {                "en": "Polling interval in seconds.",                    "de": "Abfrageintervall in Sekunden.",                   "ru": "Интервал опроса в секундах.",                     "pt": "Intervalo de sondagem em segundos.",              "nl": "Polling-interval in seconden.",                   "fr": "Intervalle d'interrogation en secondes.",         "it": "Intervallo di polling in secondi.",               "es": "Intervalo de sondeo en segundos.",                "pl": "Interwał sondowania w sekundach."},
    "Query interval": {                              "en": "Query interval",                                  "de": "Abfrageintervall",                                "ru": "интервал опроса",                                 "pt": "intervalo de pesquisa",                           "nl": "navraaginterval",                                 "fr": "intervalle d'interrogation",                      "it": "intervallo di polling",                           "es": "intervalo de sondeo",                             "pl": "interwał odpytywania"},
    "on save adapter restarts with new config immediately": {"en": "on save adapter restarts with new config immediately", "de": "Beim Speichern von Einstellungen der Adapter wird sofort neu gestartet.", "ru": "При сохранении настроек адаптеры будут перезагружены сразу.", "pt": "Ao salvar as configurações dos adaptadores, será reiniciado imediatamente.", "nl": "Wanneer u instellingen opslaat, worden de adapters onmiddellijk opnieuw gestart.", "fr": "Lors de l'enregistrement des paramètres des adaptateurs sera redémarré immédiatement.", "it": "Quando si salvano le impostazioni degli adattatori, verrà riavviato immediatamente.", "es": "Al guardar la configuración de los adaptadores se reiniciará inmediatamente.", "pl": "Po zapisaniu ustawień karty zostaną natychmiast ponownie uruchomione."},
};